package com.qvenly.qv_ms_activities.model.enums;
public enum AuditActionType {
    ACTIVITY_CREATED, ACTIVITY_EDITED, ACTIVITY_STARTED,
    ACTIVITY_FINISHED, ACTIVITY_CANCELLED,
    MEMBER_ASSIGNED, MEMBER_REMOVED, MEMBER_CONFIRMED, MEMBER_CANCELLED
}
